import { blankCase, type UseCase } from "./engine";

/* The two worked examples from the reference artifact, verbatim, plus eight
   additional ones covering the five task shapes and a deliberate spread of
   verdicts — six BUILD, one REFINE (capped by a critical risk flag), one PARK.
   An all-BUILD library would make the instrument look like a rubber stamp.
   These are "load example" seeds in the studio UI and the onboarding seed set. */
export const EXAMPLES: UseCase[] = [
  {
    ...blankCase(),
    name: "Internal policy & knowledge assistant",
    problem: "Employees ask HR and IT the same policy questions repeatedly. The team estimates roughly 30 hours a week (their internal estimate, not audited) goes to answering questions already covered in existing documentation.",
    currentCost: "≈30 staff-hours/week on repeat questions (team's own estimate); slow answers delay onboarding tasks.",
    users: "All employees; HR/IT teams are the secondary beneficiaries.",
    outcome: "Employees self-serve accurate policy answers with citations to the source document.",
    acceptanceBar: "≥90% of answers on a 100-question test set rated correct-with-citation by HR reviewers; zero fabricated policy claims tolerated.",
    dataSources: "Policy PDFs and handbook pages in SharePoint; some FAQ threads in Slack.",
    dataFormat: "documents", dataVolume: "medium", dataSensitivity: "internal", dataFreshness: "periodic",
    latency: "interactive", budget: "Pilot budget approved; small — one builder, one quarter.",
    compliance: "Internal-only; must not expose salary bands or individual HR records.",
    oversight: "spot-check", taskVolume: "high", taskShape: "lookup",
    scores: { value: 4, feasibility: 4, dataReadiness: 3, risk: 4, cost: 4, timeToValue: 4, fit: 4 },
  },
  {
    ...blankCase(),
    name: "Invoice & document triage",
    problem: "Incoming vendor invoices and contracts arrive in a shared inbox and are sorted by hand into AP categories. Misrouted documents cause payment delays; the team logs the misroutes but hasn't quantified the error rate.",
    currentCost: "1 FTE-equivalent of sorting time; unquantified rework from misrouted documents.",
    users: "Accounts-payable coordinators.",
    outcome: "Documents auto-classified into 8 routing categories with a confidence score; low-confidence items go to a human queue.",
    acceptanceBar: "≥95% routing accuracy on a labeled 500-document held-out set; every sub-threshold prediction routed to human review.",
    dataSources: "12 months of already-sorted documents in the AP drive — a natural labeled dataset, quality unverified.",
    dataFormat: "mixed", dataVolume: "large", dataSensitivity: "pii", dataFreshness: "realtime",
    latency: "batch", budget: "Not yet scoped; expected to be justified by the FTE-equivalent saved.",
    compliance: "Invoices contain vendor bank details and PII; retention rules apply.",
    oversight: "required", taskVolume: "high", taskShape: "classify",
    scores: { value: 3, feasibility: 4, dataReadiness: 4, risk: 3, cost: 3, timeToValue: 3, fit: 3 },
  },
  {
    ...blankCase(),
    name: "Support ticket deflection & reply drafting",
    problem: "Tier-1 support answers the same 40-odd question types by hand. Agents copy from a macro library that has drifted out of date, so replies are inconsistent and the macro list itself is no longer trusted.",
    currentCost: "≈1,100 tickets/week at a median 9 minutes each; two agents effectively full-time on repeat questions.",
    users: "Tier-1 support agents; end customers see the resulting reply.",
    outcome: "A drafted reply with cited help-centre articles appears in the agent console; the agent edits and sends rather than composing from scratch.",
    acceptanceBar: "≥80% of drafts sent with only minor edits, measured on 300 sampled tickets over four weeks; CSAT must not drop versus the pre-pilot baseline.",
    dataSources: "Three years of resolved Zendesk tickets, the public help centre, and the current macro library.",
    dataFormat: "documents", dataVolume: "large", dataSensitivity: "pii", dataFreshness: "periodic",
    latency: "interactive", budget: "Funded from the support-tooling line; one builder for a quarter plus agent review time.",
    compliance: "Tickets contain customer names, order history, and occasional card-last-four; drafts must never be auto-sent.",
    oversight: "required", taskVolume: "high", taskShape: "generate",
    scores: { value: 4, feasibility: 4, dataReadiness: 4, risk: 3, cost: 4, timeToValue: 4, fit: 4 },
  },
  {
    ...blankCase(),
    name: "Field service report summarization",
    problem: "Technicians dictate voice notes after each site visit; an admin transcribes them into the work-order system the next morning. Detail is lost overnight and warranty claims get rejected for thin documentation.",
    currentCost: "≈15 admin-hours/week transcribing; the team attributes roughly $40k/year of rejected warranty claims to weak write-ups (finance has not audited this figure).",
    users: "Field technicians and the service-desk admin who closes work orders.",
    outcome: "Voice notes become a structured work-order summary — parts used, fault found, follow-up needed — pre-filled for technician confirmation on the same visit.",
    acceptanceBar: "≥90% field-level accuracy against 200 admin-verified work orders; no fabricated part numbers, verified against the parts catalogue.",
    dataSources: "Two years of dictated notes with their matching completed work orders; the parts catalogue as a lookup table.",
    dataFormat: "mixed", dataVolume: "medium", dataSensitivity: "internal", dataFreshness: "periodic",
    latency: "batch", budget: "Service-operations budget; modest, and expected to pay back through warranty recovery.",
    compliance: "Customer site addresses are commercially sensitive; no consumer PII involved.",
    oversight: "spot-check", taskVolume: "medium", taskShape: "generate",
    scores: { value: 4, feasibility: 4, dataReadiness: 3, risk: 4, cost: 4, timeToValue: 4, fit: 3 },
  },
  {
    ...blankCase(),
    name: "Procurement contract clause review",
    problem: "Every inbound vendor contract is read line by line by a two-person legal team looking for the same handful of unacceptable clauses. The queue is the bottleneck in vendor onboarding, and rushed reviews are where misses happen.",
    currentCost: "Median 11 days from contract received to legal sign-off; ≈6 lawyer-hours per contract, 20 contracts a month.",
    users: "In-house counsel and the procurement managers waiting on sign-off.",
    outcome: "Each contract arrives pre-annotated against the clause playbook — indemnity, liability cap, auto-renewal, data-processing terms — with the risky span highlighted and the playbook rule cited.",
    acceptanceBar: "≥95% recall on the eight playbook clause types across 150 previously reviewed contracts; recall matters more than precision — a false flag costs a minute, a miss costs a lawsuit.",
    dataSources: "Six years of executed contracts with legal's redline history; the clause playbook as the labeling rubric.",
    dataFormat: "documents", dataVolume: "medium", dataSensitivity: "internal", dataFreshness: "periodic",
    latency: "batch", budget: "Legal-operations budget approved for a pilot; success measured on cycle time, not headcount.",
    compliance: "Contracts are commercially confidential; the tool advises and never signs, and its output is not legal advice.",
    oversight: "required", taskVolume: "medium", taskShape: "classify",
    scores: { value: 4, feasibility: 4, dataReadiness: 4, risk: 3, cost: 3, timeToValue: 3, fit: 4 },
  },
  {
    ...blankCase(),
    name: "Insurance FNOL intake extraction",
    problem: "First-notice-of-loss claims arrive by phone, email, and PDF form. Intake staff rekey them into the claims system, and the resulting typos surface days later as mis-triaged claims.",
    currentCost: "≈7 minutes of rekeying per claim at 400 claims a week; rework on mis-keyed claims adds an estimated day to cycle time.",
    users: "Claims intake coordinators; adjusters inherit whatever the intake produced.",
    outcome: "Structured claim fields — policy number, loss date, loss type, estimated severity — extracted with per-field confidence; anything below threshold is queued for a human.",
    acceptanceBar: "≥97% field accuracy on a 400-claim labeled set, with every sub-threshold field routed to review; policy numbers validated against the policy master before acceptance.",
    dataSources: "18 months of FNOL submissions with their keyed-in system records as ground truth.",
    dataFormat: "mixed", dataVolume: "large", dataSensitivity: "regulated", dataFreshness: "realtime",
    latency: "interactive", budget: "Claims-transformation programme; the largest line item is integration, not model work.",
    compliance: "Regulated insurance data with state-level retention rules; every automated extraction must be auditable back to its source document.",
    oversight: "required", taskVolume: "high", taskShape: "process",
    scores: { value: 4, feasibility: 3, dataReadiness: 4, risk: 3, cost: 3, timeToValue: 3, fit: 4 },
  },
  {
    ...blankCase(),
    name: "Marketing localization QA",
    problem: "Campaign copy is translated into nine locales by an agency, then spot-checked by whichever regional manager has time. Brand-term errors and untranslated strings reach production a few times a quarter.",
    currentCost: "≈25 manager-hours per campaign across regions; two public brand-term errors last year required pulled creative.",
    users: "Regional marketing managers and the central brand team.",
    outcome: "Every localized string is checked against the brand glossary and the source meaning before publication, with a flagged diff for the regional manager.",
    acceptanceBar: "Catch ≥90% of seeded errors in a held-out set of 500 previously corrected strings, at a false-flag rate under 10% so managers keep trusting the queue.",
    dataSources: "The brand glossary in nine locales, three years of translation memory, and the regional managers' past correction log.",
    dataFormat: "structured", dataVolume: "medium", dataSensitivity: "none", dataFreshness: "periodic",
    latency: "batch", budget: "Absorbed into the existing localization vendor spend.",
    compliance: "Public marketing copy — no sensitive data; the constraint is brand and trademark accuracy.",
    oversight: "spot-check", taskVolume: "medium", taskShape: "classify",
    scores: { value: 3, feasibility: 5, dataReadiness: 4, risk: 5, cost: 4, timeToValue: 5, fit: 3 },
  },
  {
    ...blankCase(),
    name: "Grant proposal first-draft assembly",
    problem: "The development team rewrites the same organizational boilerplate — mission, governance, past outcomes — for every funder, reshaped to each funder's priorities. Deadlines get missed for lack of drafting hours, not lack of fit.",
    currentCost: "≈30 hours per proposal, 18 proposals a year; three deadlines missed last cycle.",
    users: "Grant writers and the programme leads who supply the substance.",
    outcome: "A first draft assembled from the approved boilerplate library and prior funded proposals, shaped to the funder's stated priorities, with every factual claim traced to a source document.",
    acceptanceBar: "Grant writers rate ≥70% of drafts as 'usable starting point' across 20 proposals; zero unsourced statistics — every number traceable to an approved source.",
    dataSources: "The boilerplate library, five years of submitted proposals with funded/declined outcomes, and the annual impact reports.",
    dataFormat: "documents", dataVolume: "small", dataSensitivity: "internal", dataFreshness: "static",
    latency: "batch", budget: "Small — an operations grant covers a one-quarter pilot.",
    compliance: "Funder representations must be accurate; fabricated outcome figures would be a fraud exposure, not just an error.",
    oversight: "required", taskVolume: "low", taskShape: "generate",
    scores: { value: 4, feasibility: 4, dataReadiness: 4, risk: 4, cost: 5, timeToValue: 4, fit: 3 },
  },
  {
    ...blankCase(),
    name: "Clinical trial protocol deviation detection",
    problem: "Site monitors review visit records against the trial protocol by hand to catch deviations — missed assessments, out-of-window visits, dosing errors. Reviews lag enrollment, so deviations surface weeks after they occur.",
    currentCost: "≈2 monitor-days per site per month across 40 sites; late deviation discovery has twice triggered corrective-action plans.",
    users: "Clinical research associates and the trial's medical monitor.",
    outcome: "Visit records screened against protocol rules within a day of entry, with candidate deviations ranked by severity for monitor confirmation.",
    acceptanceBar: "≥95% recall on 12 months of adjudicated deviations, with every candidate carrying the protocol section it violates; a missed deviation is far costlier than a false positive.",
    dataSources: "EDC visit records, the protocol document and its amendments, and the adjudicated deviation log.",
    dataFormat: "mixed", dataVolume: "large", dataSensitivity: "regulated", dataFreshness: "realtime",
    latency: "batch", budget: "Not yet approved — sponsor wants a validation plan before committing.",
    compliance: "PHI under HIPAA and GDPR; GxP validation and 21 CFR Part 11 audit trails apply, and the sponsor's QA has not yet accepted an AI-assisted control.",
    oversight: "required", taskVolume: "high", taskShape: "classify",
    scores: { value: 5, feasibility: 3, dataReadiness: 3, risk: 1, cost: 2, timeToValue: 2, fit: 4 },
  },
  {
    ...blankCase(),
    name: "Executive natural-language warehouse queries",
    problem: "Executives want to ask the data warehouse questions in plain English instead of waiting on the analytics queue. The warehouse has no semantic layer, and the same metric is defined three different ways across teams.",
    currentCost: "Analytics backlog runs 2–3 weeks; roughly 40% of requests are one-off questions that never get asked again.",
    users: "Executive team and department heads; the analytics team owns whatever it returns.",
    outcome: "Plain-English questions answered from the warehouse with the SQL shown, so the asker can see how the number was derived.",
    acceptanceBar: "None agreed. 'Correct' is undefined while three conflicting definitions of revenue exist — this is the blocker, not the model.",
    dataSources: "Snowflake warehouse with ~1,400 tables, minimal documentation, no semantic layer, and no metric dictionary.",
    dataFormat: "structured", dataVolume: "large", dataSensitivity: "internal", dataFreshness: "realtime",
    latency: "interactive", budget: "No budget line; raised as an idea in a leadership offsite.",
    compliance: "Financial figures shown to executives would inform reporting decisions — a wrong number that looks authoritative is the core risk.",
    oversight: "none", taskVolume: "low", taskShape: "lookup",
    scores: { value: 2, feasibility: 2, dataReadiness: 2, risk: 2, cost: 2, timeToValue: 1, fit: 2 },
  },
];
