/* =============================================================
   Build Kickoff — Markdown export (BK-5). Pure renderer.

   The disclaimer and the independent critic audit are bound HERE, at the data
   layer: renderPlanMarkdown takes a non-null plan AND audit and always emits
   both, so there is no code path that produces a plan document without its
   audit and the decision-support disclaimer attached (P0.9).
   ============================================================= */

import type { IntegratedPlan, CriticAudit, Provenance } from "./contracts";

export const DECISION_SUPPORT_DISCLAIMER =
  "> **Decision-support, not a guarantee.** This plan was generated by a bounded LLM pipeline from your evaluation inputs. It is a defensible starting point, not a validated design — every estimate is labeled and must be checked against reality. An independent critic audit is attached below and travels with this document; read it alongside the plan. No benchmark, vendor, or ROI figure here should be treated as verified.";

const bullet = (s: string) => `- ${s}`;

function renderAudit(a: CriticAudit): string {
  const lines = [
    "## Independent critic audit",
    "",
    `**Critic verdict:** ${a.verdict}`,
    "",
    "**Load-bearing gaps**",
    ...a.gaps.map((g) => bullet(`**${g.title}** — ${g.detail}`)),
  ];
  if (a.topFixes.length) lines.push("", "**Top fixes**", ...a.topFixes.map(bullet));
  if (a.overclaims.length) lines.push("", "**Overclaims flagged**", ...a.overclaims.map(bullet));
  if (a.fabricationScan.length)
    lines.push(
      "",
      "**Fabrication scan**",
      ...a.fabricationScan.map((f) => bullet(`\`${f.quote}\` → ${f.verdict}`)),
    );
  if (a.consistencyIssues.length)
    lines.push("", "**Consistency issues**", ...a.consistencyIssues.map(bullet));
  lines.push(
    "",
    `**Acceptance bar is the spine:** ${a.acceptanceBarSpine.isSpine ? "yes" : "NO"} — ${a.acceptanceBarSpine.evidence}`,
    `**Verdict integrity:** ${a.verdictIntegrity.pass ? "pass" : "FAIL"} — ${a.verdictIntegrity.note}`,
  );
  return lines.join("\n");
}

/** Single Markdown artifact: plan + attached audit + disclaimer + provenance.
 *  Requires both plan and audit — an unaudited/partial plan is not exportable. */
export function renderPlanMarkdown(input: {
  plan: IntegratedPlan;
  audit: CriticAudit;
  provenance: Provenance;
  version: number;
}): string {
  const { plan, audit, provenance, version } = input;
  const sec = (s?: { heading: string; markdown: string }) =>
    s ? [`### ${s.heading}`, "", s.markdown, ""] : [];

  const flows = plan.dataFlows.map(
    (f) => `**${f.name}:** ${f.steps.join(" → ")}`,
  );
  const miles = plan.milestones.map((m) =>
    `- **${m.phase}** — ${m.goal}${m.duration ? ` _(${m.duration})_` : ""}. Exit: ${m.exitCriterion}.${m.ownerOfRisk ? ` Risk owner: ${m.ownerOfRisk}.` : ""}`,
  );

  const parts = [
    `# Build Kickoff — ${plan.taskShape || "plan"} (${plan.verdict}) · v${version}`,
    "",
    DECISION_SUPPORT_DISCLAIMER,
    "",
    "## Executive summary",
    "",
    plan.executiveSummary,
    "",
    `**Architecture pattern:** ${plan.architecturePattern}`,
    "",
    "## Plan",
    "",
    ...sec(plan.sections.architecture),
    ...sec(plan.sections.dataPipeline),
    ...sec(plan.sections.evaluation),
    ...sec(plan.sections.governance),
    ...sec(plan.sections.delivery),
    ...sec(plan.sections.integrationNotes),
    "## Data flows",
    "",
    ...flows,
    "",
    "## Milestones",
    "",
    ...miles,
    "",
  ];

  if (plan.refineGate) {
    parts.push(
      "## Phase-0 refine gate",
      "",
      "**Conditions to resolve:**",
      ...plan.refineGate.conditions.map(bullet),
      "",
      "**No-go conditions (any true → stop):**",
      ...plan.refineGate.noGoConditions.map(bullet),
      "",
    );
  }

  if (plan.assumptions.length) {
    parts.push("## Assumptions & labeled estimates", "", ...plan.assumptions.map(bullet), "");
  }

  parts.push(
    renderAudit(audit),
    "",
    "---",
    "",
    "### Provenance",
    "",
    `- Engine outputs hash: \`${provenance.engineOutputsHash}\``,
    `- Prompt roster version: \`${provenance.promptRosterVersion}\``,
    `- Model: \`${provenance.model}\``,
    `- Verdict at generation: **${provenance.verdictAtGeneration}**`,
    `- Case version: \`${provenance.caseVersion}\``,
    "",
    DECISION_SUPPORT_DISCLAIMER,
    "",
  );

  return parts.join("\n");
}
